name: LobbyCore
version: '${project.version}'
main: com.lobby.LobbyPlugin
api-version: '1.21'
softdepend: [HeadDatabase]
commands:
  lobby:
    description: Commande principale du lobby
    aliases: [l, hub]
    permission: lobby.use
  coins:
    description: Affiche votre solde de coins
    aliases: [money, balance]
    permission: lobby.economy.use
  tokens:
    description: Affiche votre solde de tokens
    permission: lobby.economy.use
  pay:
    description: Transfère des coins à un joueur
    permission: lobby.economy.pay
  top:
    description: Classement économique
    permission: lobby.economy.use
  shop:
    description: Ouvre la boutique du lobby
    permission: lobby.shop.use
  jeux:
    description: Ouvre le menu des jeux
    permission: lobby.use
  amis:
    description: Ouvre le menu des amis
    permission: lobby.use
  serveurs:
    description: Ouvre le sélecteur de serveurs
    aliases: [server]
    permission: lobby.use
  profil:
    description: Affiche le profil du joueur
    permission: lobby.use
  discord:
    description: Lie son compte Discord
    permission: lobby.discord.link
  lobbyadmin:
    description: Commandes d'administration du lobby
    aliases: [ladmin]
    permission: lobby.admin
  npc:
    description: Gestion des PNJ
    permission: lobby.admin.npc
permissions:
  lobby.use:
    default: true
  lobby.shop.use:
    default: true
  lobby.discord.link:
    default: true
  lobby.admin:
    default: op
  lobby.economy.use:
    default: true
  lobby.economy.pay:
    default: true
  lobby.economy.view:
    default: op
  lobby.admin.economy:
    default: op
  lobby.admin.hologram:
    default: op
  lobby.admin.npc:
    default: op
  lobby.admin.bypass:
    default: op
  lobby.admin.shop:
    default: op
