title: '&8» &dConfidentialité & Social'
size: 54
design:
  primary_border: { material: 'LIME_STAINED_GLASS_PANE', slots: [0,1,2,6,7,8,9,17,36,44,45,46,52,53] }
  secondary_border: { material: 'GRAY_STAINED_GLASS_PANE', slots: [39,40,41] }
items:
  toggle-requests:
    slot: 20
    material: 'hdb:13389'
    name: '&b&lRecevoir les Demandes d''Ami'
    lore: ['&r', '&7Contrôlez si les joueurs peuvent', '&7vous envoyer des demandes.', '&r', '&b▸ Statut : %friend_requests_status%', '&r', '&e▶ Cliquez pour basculer']
    action: '[COMMAND] friends settings toggle requests'
  toggle-pms:
    slot: 22
    material: 'hdb:3581'
    name: '&b&lRecevoir les Messages Privés'
    lore: ['&r', '&7Choisissez qui peut vous envoyer', '&7des messages privés.', '&r', '&b▸ Statut : %messaging_status%', '&r', '&e▶ Cliquez pour changer']
    action: '[COMMAND] friends settings toggle pms'
  toggle-visibility:
    slot: 24
    material: 'hdb:32010'
    name: '&b&lVisibilité du Statut'
    lore: ['&r', '&7Choisissez qui peut voir que', '&7vous êtes en ligne.', '&r', '&b▸ Statut : %visibility_status%', '&r', '&e▶ Cliquez pour changer']
    action: '[COMMAND] friends settings toggle visibility'
  return-to-friends:
    slot: 50
    material: 'hdb:9334'
    name: '&c&lRetour'
    action: '[MENU] amis_menu'
