title: '&8» &aMes Amis'
size: 54
design:
  primary_border: { material: 'LIME_STAINED_GLASS_PANE', slots: [0,1,2,6,7,8,9,17,36,44,45,46,52,53] }
  secondary_border: { material: 'GRAY_STAINED_GLASS_PANE', slots: [39,40,41] }
items:
  add-friend:
    slot: 3
    material: 'hdb:23533'
    name: '&a&lAjouter un Ami'
    lore: ['&r', '&7Utilisez &e/amis add <pseudo>', '&7pour envoyer une demande.', '&r', '&e▶ Cliquez pour lancer l\'invitation']

  sort-search:
    slot: 5
    material: 'hdb:176'
    name: '&e&lTrier & Rechercher'
    lore:
      - '&r'
      - '&7Organisez votre liste d\'amis'
      - '&7ou trouvez quelqu\'un rapidement.'
      - '&r'
      - '&b▸ Tri actuel: &a%friends_sort_mode%'
      - '&r'
      - '&e▶ Clic-gauche pour trier'
      - '&e▶ Clic-droit pour rechercher'

  requests:
    slot: 7
    material: 'hdb:23528'
    name: '&e&lDemandes Reçues'
    enchanted: '%friend_requests_count% > 0'
    lore: ['&r', '&7Gérez les demandes d\'ami que', '&7vous avez reçues.', '&r', '&b▸ En attente : &6%friend_requests_count%', '&r', '&e▶ Cliquez pour voir']
    action: '[MENU] amis_requests_menu'

  settings:
    slot: 49
    material: 'hdb:1218'
    name: '&d&lConfidentialité & Social'
    lore: ['&r', '&7Gérez vos paramètres de' , '&7confidentialité et de notification.', '&r', '&e▶ Cliquez pour configurer']
    action: '[MENU] amis_settings_menu'

  return-to-profile:
    slot: 50
    material: 'hdb:9334'
    name: '&c&lRetour au Profil'
    action: '[MENU] profil_menu'
