menu:
  id: "audio_settings_menu"
  title: "&8» &6Paramètres Audio"
  size: 27

  items:
    ui_sounds:
      slot: 11
      material: "PLAYER_HEAD"
      head: "hdb:7439"
      name: "&a&lSons d'Interface"
      lore:
        - "&7Sons joués lors des interactions"
        - "&7avec les menus et boutons."
        - "&r"
        - "&8▸ &7Statut: %setting_ui_sounds_display%"
        - "&r"
        - "&e⚡ Exemples de sons :"
        - "&7- Clic sur les boutons"
        - "&7- Ouverture/fermeture de menus"
        - "&7- Validation d'actions"
        - "&7- Notifications importantes"
        - "&r"
        - "&a▶ Cliquez pour basculer !"
      actions:
        - "[SETTING_TOGGLE] UI_SOUNDS"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    particles:
      slot: 13
      material: "PLAYER_HEAD"
      head: "hdb:8664"
      name: "&b&lEffets de Particules"
      lore:
        - "&7Effets visuels et particules"
        - "&7dans le lobby et les menus."
        - "&r"
        - "&8▸ &7Statut: %setting_particles_display%"
        - "&r"
        - "&e⚡ Types d'effets :"
        - "&7- Particules autour des PNJ"
        - "&7- Effets lors des actions"
        - "&7- Animations de menus"
        - "&7- Effets de téléportation"
        - "&r"
        - "&c⚠ Peut affecter les performances"
        - "&r"
        - "&a▶ Cliquez pour basculer !"
      actions:
        - "[SETTING_TOGGLE] PARTICLES"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    music:
      slot: 15
      material: "PLAYER_HEAD"
      head: "hdb:2113"
      name: "&d&lMusique d'Ambiance"
      lore:
        - "&7Musique douce jouée en"
        - "&7arrière-plan dans le lobby."
        - "&r"
        - "&8▸ &7Statut: %setting_music_display%"
        - "&r"
        - "&e⚡ Caractéristiques :"
        - "&7- Volume faible et discret"
        - "&7- Mélodies relaxantes"
        - "&7- Ne couvre pas les sons de jeu"
        - "&7- S'arrête automatiquement en jeu"
        - "&r"
        - "&6💡 Idéal pour l'ambiance !"
        - "&r"
        - "&a▶ Cliquez pour basculer !"
      actions:
        - "[SETTING_TOGGLE] MUSIC"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    back:
      slot: 22
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir aux paramètres."
      actions:
        - "[MENU] settings_menu"
        - "[SOUND] BLOCK_STONE_BUTTON_CLICK_OFF"
