menu:
  id: "clan_kick_confirm"
  title: "&8» &4Confirmer l'Expulsion"
  size: 27
  items:
    confirm:
      slot: 11
      material: LIME_CONCRETE
      name: "&a&lConfirmer"
      lore:
        - "&7Expulser &f%clan_target_name% &7du clan."
        - "&cCette action est immédiate !"
      actions:
        - "[COMMAND] clan kick %clan_target_name%"
        - "[CLOSE_MENU]"

    cancel:
      slot: 15
      material: RED_CONCRETE
      name: "&c&lAnnuler"
      lore:
        - "&7Retourner à la gestion du membre."
      actions:
        - "[MENU] clan_member_management_menu"

    info:
      slot: 13
      head: "%clan_target_name%"
      name: "&6%clan_target_name%"
      lore:
        - "&7Rang: &f%clan_target_rank_display%"
        - "&7Contribution: &e%clan_target_contribution%"
