menu:
  id: "clan_transfer_confirm"
  title: "&8» &6Transférer le Leadership"
  size: 27
  items:
    confirm:
      slot: 11
      material: LIME_CONCRETE
      name: "&6&lConfirmer le Transfert"
      lore:
        - "&7Donner le rôle de leader à &f%clan_target_name%"
        - "&cVous deviendrez Co-Leader."
      actions:
        - "[COMMAND] clan transfer %clan_target_name%"
        - "[CLOSE_MENU]"

    cancel:
      slot: 15
      material: RED_CONCRETE
      name: "&c&lAnnuler"
      lore:
        - "&7Retourner à la gestion du membre."
      actions:
        - "[MENU] clan_member_management_menu"

    info:
      slot: 13
      head: "%clan_target_name%"
      name: "&6%clan_target_name%"
      lore:
        - "&7Rang actuel: &f%clan_target_rank_display%"
        - "&7Rejoint le: &f%clan_target_join_date%"
