menu:
  id: "clan_ban_confirm"
  title: "&8» &8Bannir un Membre"
  size: 27
  design_template: "social"
  items:
    confirm:
      slot: 11
      material: LIME_CONCRETE
      name: "&c&lConfirmer le Bannissement"
      lore:
        - "&7Bannir définitivement &f%clan_target_name%&7."
        - "&cCette action est irréversible !"
      actions:
        - "[COMMAND] clan ban %clan_target_name%"
        - "[CLOSE_MENU]"

    cancel:
      slot: 15
      material: RED_CONCRETE
      name: "&c&lAnnuler"
      lore:
        - "&7Retourner à la gestion du membre."
      actions:
        - "[MENU] clan_member_management_menu"

    info:
      slot: 13
      head: "%clan_target_name%"
      name: "&6%clan_target_name%"
      lore:
        - "&7Rang: &f%clan_target_rank_display%"
        - "&7Dernière connexion: &f%clan_target_last_seen%"
