menu:
  id: "clan_menu"
  title: "&8» &c&lGestion de Clan"
  size: 54
  design_template: "social"

  items:
    my_clan:
      slot: 19
      material: "PLAYER_HEAD"
      head: "hdb:8971"
      name: "&c&lMon Clan"
      lore:
        - "&7Informations sur votre clan actuel"
        - "&r"
        - "&8▸ &7Clan: &c%clan_name%"
        - "&8▸ &7Rang: &6%clan_rank%"
        - "&8▸ &7Membres: &a%clan_members%/%clan_max%"
        - "&8▸ &7Points: &e%clan_points%"
        - "&r"
        - "&a▶ Cliquez pour voir les détails !"
      actions:
        - "[MENU] clan_info_menu"

    clan_members:
      slot: 21
      material: "PLAYER_HEAD"
      head: "hdb:9969"
      name: "&e&lMembres du Clan"
      lore:
        - "&7Gérez les membres de votre clan"
        - "&r"
        - "&8▸ &7Membres connectés: &a%clan_online%/%clan_members%"
        - "&8▸ &7Dernière activité: &f%clan_last_activity%"
        - "&8▸ &7Permissions: &6%clan_permissions%"
        - "&r"
        - "&a▶ Cliquez pour gérer !"
      actions:
        - "[CLAN_MEMBERS]"

    clan_ranks:
      slot: 23
      material: "PLAYER_HEAD"
      head: "hdb:1218"
      name: "&d&lRangs et Permissions"
      lore:
        - "&7Configurez les rangs de votre clan"
        - "&r"
        - "&8▸ &7Votre niveau: &6%clan_player_level%"
        - "&8▸ &7Permissions disponibles: &d%clan_available_perms%"
        - "&8▸ &7Rangs configurés: &e%clan_ranks_count%"
        - "&r"
        - "&6⚠ Nécessite rang Officier+"
      actions:
        - "[MENU] clan_ranks_menu"

    clan_treasury:
      slot: 25
      material: "PLAYER_HEAD"
      head: "hdb:35472"
      name: "&a&lTrésor du Clan"
      lore:
        - "&7Gérez les ressources du clan"
        - "&r"
        - "&8▸ &7Coins du clan: &e%clan_coins%"
        - "&8▸ &7Contributions mensuelles: &6%clan_contributions%"
        - "&8▸ &7Accès coffre: &b%clan_vault_access%"
        - "&r"
        - "&a▶ Cliquez pour accéder !"
      actions:
        - "[CLAN_VAULT]"

    clan_shop:
      slot: 29
      material: "PLAYER_HEAD"
      head: "hdb:38878"
      name: "&6&lBoutique du Clan"
      lore:
        - "&7Investissez les coins du clan"
        - "&7dans des améliorations et cosmétiques."
        - "&r"
        - "&8▶ &7Ouvrir la boutique"
      actions:
        - "[MENU] clan_shop_menu"

    clan_wars:
      slot: 31
      material: "PLAYER_HEAD"
      head: "hdb:38878"
      name: "&b&lGuerres de Clans"
      lore:
        - "&7Participez aux guerres épiques !"
        - "&r"
        - "&8▸ &7Guerre actuelle: &f%clan_war_status%"
        - "&8▸ &7Victoires: &a%clan_war_wins%"
        - "&8▸ &7Défaites: &c%clan_war_losses%"
        - "&8▸ &7Ratio: &6%clan_war_ratio%"
        - "&r"
        - "&c⚔ Cliquez pour les guerres !"
      actions:
        - "[MENU] clan_wars_menu"

    clan_create:
      slot: 48
      material: "PLAYER_HEAD"
      head: "hdb:12654"
      name: "&6&lCréer un Clan"
      lore:
        - "&7Créez votre propre clan !"
        - "&r"
        - "&8▸ &7Coût: &e10,000 coins"
        - "&8▸ &7Membres max: &a20 joueurs"
        - "&8▸ &7Avantages: &fCoffre, Guerres, Chat privé"
        - "&r"
        - "&a▶ Cliquez pour créer !"
      actions:
        - "[MENU] clan_creation_menu"

    clan_delete:
      slot: 33
      material: "PLAYER_HEAD"
      head: "hdb:60776"
      name: "&c&lSupprimer le Clan"
      lore:
        - "&7Supprimez définitivement votre clan."
        - "&7Cette action est irréversible !"
        - "&r"
        - "&8▸ &7Membres expulsés"
        - "&8▸ &7Trésor perdu"
        - "&8▸ &7Données effacées"
        - "&r"
        - "&c⚠ Nécessite confirmation"
        - "&c▶ Cliquez pour supprimer !"
      actions:
        - "[CLAN_DELETE_CONFIRM]"

    clan_join:
      slot: 50
      material: "PLAYER_HEAD"
      head: "hdb:23022"
      name: "&e&lRejoindre un Clan"
      lore:
        - "&7Explorez les clans disponibles"
        - "&r"
        - "&8▸ &7Clans ouverts: &a%clans_open_count%"
        - "&8▸ &7Clans avec invitations: &e%clans_invite_count%"
        - "&8▸ &7Popularité: &fTop clans actifs"
        - "&r"
        - "&a▶ Cliquez pour explorer !"
      actions:
        - "[MENU] clan_browse_menu"

    back:
      slot: 49
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir au menu précédent"
        - "&r"
        - "&a▶ Cliquez pour revenir !"
      actions:
        - "[MENU] profile_main"
