menu:
  id: "cosmetiques_menu"
  title: "&8» &dCosmétiques"
  size: 45
  fill_material: "PINK_STAINED_GLASS_PANE"

  items:
    particles:
      slot: 20
      material: "GHAST_TEAR"
      name: "&dParticules"
      lore:
        - "&7Sélectionne un effet visuel"
        - "&7unique pour ton personnage."
      actions:
        - "[COMMAND] cosmetics open particles"

    morphs:
      slot: 22
      material: "CREEPER_HEAD"
      name: "&aMorphs"
      lore:
        - "&7Transforme-toi en créatures"
        - "&7et amuse-toi avec tes amis."
      actions:
        - "[COMMAND] cosmetics open morphs"

    gadgets:
      slot: 24
      material: "BLAZE_ROD"
      name: "&bGadgets"
      lore:
        - "&7Débloque des gadgets amusants"
        - "&7et interactifs."
      actions:
        - "[COMMAND] cosmetics open gadgets"

    back:
      slot: 40
      material: "ARROW"
      name: "&cRetour"
      lore:
        - "&7Revenir à la boutique"
      actions:
        - "[MENU] shop_menu"
