menu:
  id: "friend_management"
  title: "&8» &aGestion des Amis"
  size: 45

  items:
    friend_remove:
      slot: 20
      head: "hdb:9334"
      name: "&c&lRetirer des Amis"
      lore:
        - "&7Retirer %friend_name% de votre"
        - "&7liste d'amis."
        - "&r"
        - "&8▸ &7Statut: %friend_status%"
        - "&8▸ &7Amis depuis: %friendship_date%"
        - "&r"
        - "&c▶ Cliquez pour retirer !"
      actions:
        - "[MENU] friend_remove_confirm"

    friend_block:
      slot: 22
      head: "hdb:46237"
      name: "&8&lBloquer"
      lore:
        - "&7Bloquer %friend_name%."
        - "&7Il ne pourra plus vous contacter."
        - "&r"
        - "&c⚠ Cette action le retirera"
        - "&c⚠ également de vos amis !"
        - "&r"
        - "&8▶ Cliquez pour bloquer !"
      actions:
        - "[MENU] friend_block_confirm"
