menu:
  id: "friends_menu"
  title: "&8» &a&lGestion d'Amis"
  size: 54
  design_template: "social"

  items:
    friends_online:
      slot: 20
      material: "PLAYER_HEAD"
      head: "hdb:9945"
      name: "&a&lAmis En Ligne"
      lore:
        - "&7Vos amis actuellement connectés"
        - "&r"
        - "&8▸ &7Amis en ligne: &a%friends_online%/%friends_total%"
        - "&8▸ &7Serveurs populaires: &b%friends_popular_servers%"
        - "&8▸ &7Activité récente: &d%friends_recent_activity%"
        - "&r"
        - "&a▶ Cliquez pour voir la liste !"
      actions:
        - "[FRIENDS_ONLINE]"

    friend_requests:
      slot: 22
      material: "PLAYER_HEAD"
      head: "hdb:1455"
      name: "&e&lDemandes d'Amis"
      lore:
        - "&7Gérez vos demandes d'amitié"
        - "&r"
        - "&8▸ &7Demandes reçues: &e%friend_requests_received%"
        - "&8▸ &7Demandes envoyées: &b%friend_requests_sent%"
        - "&8▸ &7En attente depuis: &f%friend_requests_oldest%"
        - "&r"
        - "&e▶ Cliquez pour gérer !"
      actions:
        - "[FRIEND_REQUESTS]"

    friends_all:
      slot: 24
      material: "PLAYER_HEAD"
      head: "hdb:13389"
      name: "&b&lTous mes Amis"
      lore:
        - "&7Liste complète de vos amis"
        - "&r"
        - "&8▸ &7Total d'amis: &a%friends_total%"
        - "&8▸ &7Amis favoris: &6%friends_favorites%"
        - "&8▸ &7Dernière connexion: &f%friends_last_seen%"
        - "&r"
        - "&b▶ Cliquez pour parcourir !"
      actions:
        - "[MENU] friends_all_menu"

    friend_add:
      slot: 28
      material: "PLAYER_HEAD"
      head: "hdb:7439"
      name: "&d&lAjouter un Ami"
      lore:
        - "&7Envoyez une demande d'amitié"
        - "&r"
        - "&8▸ &7Tapez le nom dans le chat"
        - "&8▸ &7Limites: &d%friend_limits%"
        - "&8▸ &7Statut: &f%friend_request_status%"
        - "&r"
        - "&d▶ Cliquez pour ajouter !"
      actions:
        - "[FRIEND_ADD]"

    friend_settings:
      slot: 30
      material: "PLAYER_HEAD"
      head: "hdb:8537"
      name: "&6&lParamètres d'Amis"
      lore:
        - "&7Configurez vos préférences"
        - "&r"
        - "&8▸ &7Demandes automatiques: &f%friend_auto_accept%"
        - "&8▸ &7Notifications: &6%friend_notifications%"
        - "&8▸ &7Visibilité: &b%friend_visibility%"
        - "&r"
        - "&6▶ Cliquez pour configurer !"
      actions:
        - "[MENU] friend_settings_menu"

    friends_favorites:
      slot: 32
      material: "PLAYER_HEAD"
      head: "hdb:12654"
      name: "&c&lAmis Favoris"
      lore:
        - "&7Vos amis les plus proches"
        - "&r"
        - "&8▸ &7Favoris marqués: &6%friends_favorites_count%"
        - "&8▸ &7Notifications prioritaires activées"
        - "&8▸ &7Accès rapide aux invitations"
        - "&r"
        - "&c▶ Cliquez pour voir !"
      actions:
        - "[MENU] friends_favorites_menu"

    back:
      slot: 49
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir au menu précédent"
        - "&r"
        - "&a▶ Cliquez pour revenir !"
      actions:
        - "[MENU] profile_main"
