menu:
  id: "groups_menu"
  title: "&8» &e&lGestion de Groupes"
  size: 54
  design_template: "social"

  items:
    current_group:
      slot: 20
      material: "PLAYER_HEAD"
      head: "hdb:9723"
      name: "&e&lMon Groupe Actuel"
      lore:
        - "&7Informations sur votre groupe"
        - "&r"
        - "&8▸ &7Groupe: &e%group_name%"
        - "&8▸ &7Leader: &6%group_leader%"
        - "&8▸ &7Membres: &a%group_members%/%group_max%"
        - "&8▸ &7Mode de jeu: &b%group_gamemode%"
        - "&8▸ &7Statut: &f%group_status%"
        - "&r"
        - "&e▶ Cliquez pour gérer !"
      actions:
        - "[MENU] group_manage_menu"

    group_create:
      slot: 22
      material: "PLAYER_HEAD"
      head: "hdb:38878"
      name: "&a&lCréer un Groupe"
      lore:
        - "&7Créez un nouveau groupe de jeu"
        - "&r"
        - "&8▸ &7Taille max: &a8 joueurs"
        - "&8▸ &7Modes supportés: &fTous les jeux"
        - "&8▸ &7Durée max: &e2 heures"
        - "&8▸ &7Coût: &aGratuit"
        - "&r"
        - "&a▶ Cliquez pour créer !"
      actions:
        - "[GROUP_CREATE]"

    group_join:
      slot: 24
      material: "PLAYER_HEAD"
      head: "hdb:1218"
      name: "&b&lRejoindre un Groupe"
      lore:
        - "&7Rejoignez un groupe existant"
        - "&r"
        - "&8▸ &7Groupes ouverts: &a%groups_open%"
        - "&8▸ &7Groupes d'amis: &e%groups_friends%"
        - "&8▸ &7Invitations reçues: &b%group_invitations%"
        - "&r"
        - "&b▶ Cliquez pour explorer !"
      actions:
        - "[MENU] group_browse_menu"

    group_invite:
      slot: 28
      material: "PLAYER_HEAD"
      head: "hdb:7439"
      name: "&d&lInviter des Joueurs"
      lore:
        - "&7Invitez des amis dans votre groupe"
        - "&r"
        - "&8▸ &7Amis en ligne: &a%friends_online_count%"
        - "&8▸ &7Places disponibles: &e%group_slots_free%"
        - "&8▸ &7Invitations envoyées: &b%group_invites_sent%"
        - "&r"
        - "&d▶ Cliquez pour inviter !"
      actions:
        - "[MENU] group_invite_menu"

    group_queue:
      slot: 30
      material: "PLAYER_HEAD"
      head: "hdb:23022"
      name: "&6&lFiles d'Attente"
      lore:
        - "&7Rejoignez une file d'attente"
        - "&r"
        - "&8▸ &7Files disponibles: &f%queue_available%"
        - "&8▸ &7Temps d'attente moyen: &b%queue_wait_time%"
        - "&8▸ &7Joueurs en file: &e%queue_players%"
        - "&r"
        - "&6▶ Cliquez pour rejoindre !"
      actions:
        - "[MENU] queue_menu"

    group_settings:
      slot: 32
      material: "PLAYER_HEAD"
      head: "hdb:8537"
      name: "&c&lParamètres de Groupe"
      lore:
        - "&7Configurez vos préférences"
        - "&r"
        - "&8▸ &7Invitations automatiques: &f%group_auto_accept%"
        - "&8▸ &7Mode préféré: &b%group_preferred_mode%"
        - "&8▸ &7Visibilité: &e%group_visibility%"
        - "&r"
        - "&c▶ Cliquez pour configurer !"
      actions:
        - "[MENU] group_settings_menu"

    back:
      slot: 49
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir au menu précédent"
        - "&r"
        - "&a▶ Cliquez pour revenir !"
      actions:
        - "[MENU] profil_menu"
