menu:
  id: 'jeux_menu'
  title: '&8» &aMenu des Jeux'
  size: 54
  items:
    decor_slots: '0,1,2,6,7,8,9,17,45,53'
    decor_item: { material: 'ORANGE_STAINED_GLASS_PANE', name: '&7', action: '[NONE]' }
    slot_20:
      material: 'hdb:67957'
      name: '&c&lBedWars'
      lore: ['&7Le mode de jeu le plus apprécié !', '&r', '&8▸ &7Joueurs: &a%lobby_online_bedwars%']
      action: '[SERVER_SEND] bedwars'
    slot_49:
      material: 'PLAYER_HEAD'
      name: '&6&lMon Profil'
      lore: ['&7Consultez vos statistiques.', '&r', '&a▶ Cliquez pour voir !']
      action: '[MENU] profil_menu'
