menu:
  id: "language_menu"
  title: "&8» &fSélection de Langue"
  size: 27

  items:
    francais:
      slot: 11
      material: "PLAYER_HEAD"
      head: "hdb:2736"
      name: "&c&l🇫🇷 Français"
      lore:
        - "&7Langue française"
        - "&r"
        - "&8▸ &7Statut: %lang_fr_status%"
        - "&r"
        - "&a▶ Cliquez pour sélectionner !"
      actions:
        - "[SETTING_LANGUAGE] fr"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    english:
      slot: 13
      material: "PLAYER_HEAD"
      head: "hdb:2735"
      name: "&f&l🇬🇧 English"
      lore:
        - "&7English language"
        - "&r"
        - "&8▸ &7Status: %lang_en_status%"
        - "&r"
        - "&a▶ Click to select!"
      actions:
        - "[SETTING_LANGUAGE] en"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    espanol:
      slot: 15
      material: "PLAYER_HEAD"
      head: "hdb:2738"
      name: "&e&l🇪🇸 Español"
      lore:
        - "&7Idioma español"
        - "&r"
        - "&8▸ &7Estado: %lang_es_status%"
        - "&r"
        - "&a▶ ¡Haz clic para seleccionar!"
      actions:
        - "[SETTING_LANGUAGE] es"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    retour:
      slot: 22
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir au menu profil."
      actions:
        - "[MENU] profil_menu"
