menu:
  id: "language_menu"
  title: "&8» &fSélection de Langue"
  size: 27
  borders:
    - slots: [0,1,2,6,7,8,9,17,18,26]
      material: "BLUE_STAINED_GLASS_PANE"
      name: "&7"

  items:
    french:
      slot: 11
      material: "PLAYER_HEAD"
      head: "hdb:2736"
      name: "&c&l🇫🇷 Français"
      lore:
        - "&7Langue française"
        - "&r"
        - "&8▸ &7Statut: %lang_fr_status%"
        - "&r"
        - "&a▶ Cliquez pour sélectionner !"
      actions:
        - "[COMMAND] language set fr"

    english:
      slot: 13
      material: "PLAYER_HEAD"
      head: "hdb:2735"
      name: "&f&l🇬🇧 English"
      lore:
        - "&7English language"
        - "&r"
        - "&8▸ &7Status: %lang_en_status%"
        - "&r"
        - "&a▶ Click to select!"
      actions:
        - "[COMMAND] language set en"

    spanish:
      slot: 15
      material: "PLAYER_HEAD"
      head: "hdb:2738"
      name: "&e&l🇪🇸 Español"
      lore:
        - "&7Idioma español"
        - "&r"
        - "&8▸ &7Estado: %lang_es_status%"
        - "&r"
        - "&a▶ ¡Haz clic para seleccionar!"
      actions:
        - "[COMMAND] language set es"

    back:
      slot: 22
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir au menu profil."
      actions:
        - "[MENU] profile_main"
