menu:
  id: "notifications_menu"
  title: "&8» &cGestion des Notifications"
  size: 27

  items:
    friend_notifications:
      slot: 11
      material: "PLAYER_HEAD"
      head: "hdb:9945"
      name: "&a&lNotifications d'Amis"
      lore:
        - "&7Recevez des notifications quand"
        - "&7vos amis se connectent ou jouent."
        - "&r"
        - "&8▸ &7Statut: %setting_friend_notifications_display%"
        - "&r"
        - "&e⚡ Types de notifications :"
        - "&7- Connexion d'un ami"
        - "&7- Ami qui rejoint un jeu"
        - "&7- Demandes d'amis reçues"
        - "&r"
        - "&a▶ Cliquez pour basculer !"
      actions:
        - "[SETTING_TOGGLE] FRIEND_NOTIFICATIONS"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    clan_notifications:
      slot: 13
      material: "PLAYER_HEAD"
      head: "hdb:8971"
      name: "&c&lNotifications de Clan"
      lore:
        - "&7Recevez des notifications pour"
        - "&7les activités de votre clan."
        - "&r"
        - "&8▸ &7Statut: %setting_clan_notifications_display%"
        - "&r"
        - "&e⚡ Types de notifications :"
        - "&7- Nouveaux membres"
        - "&7- Promotions/rétrogradations"
        - "&7- Guerres de clans"
        - "&7- Messages importants"
        - "&r"
        - "&a▶ Cliquez pour basculer !"
      actions:
        - "[SETTING_TOGGLE] CLAN_NOTIFICATIONS"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    system_notifications:
      slot: 15
      material: "PLAYER_HEAD"
      head: "hdb:1455"
      name: "&e&lNotifications Système"
      lore:
        - "&7Recevez des notifications pour"
        - "&7les événements du serveur."
        - "&r"
        - "&8▸ &7Statut: %setting_system_notifications_display%"
        - "&r"
        - "&e⚡ Types de notifications :"
        - "&7- Nouveautés et mises à jour"
        - "&7- Événements spéciaux"
        - "&7- Maintenance programmée"
        - "&7- Récompenses disponibles"
        - "&r"
        - "&a▶ Cliquez pour basculer !"
      actions:
        - "[SETTING_TOGGLE] SYSTEM_NOTIFICATIONS"
        - "[SOUND] BLOCK_NOTE_BLOCK_PLING"

    back:
      slot: 22
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir aux paramètres."
      actions:
        - "[MENU] settings_menu"
        - "[SOUND] BLOCK_STONE_BUTTON_CLICK_OFF"
