menu:
  id: 'profil_menu'
  title: '&8» &6Mon Profil'
  size: 54
  items:
    decor_slots: '0,1,2,6,7,8,9,17,45,53'
    decor_item: { material: 'BLUE_STAINED_GLASS_PANE', name: '&7', action: '[NONE]' }
    slot_20:
      material: 'PLAYER_HEAD'
      name: '&b&lMes Statistiques'
      lore: ['&7Consultez toutes vos performances.', '&r', '&a▶ Cliquez pour voir le détail !']
      action: '[MENU] stats_detailed_menu'
    slot_24:
      material: 'hdb:1218'
      name: '&d&lParamètres'
      lore: ['&7Personnalisez votre expérience.', '&r', '&a▶ Cliquez pour configurer !']
      action: '[MENU] settings_menu'
    slot_49:
      material: 'hdb:9334'
      name: '&c&lRetour'
      lore: ['&7Retourner au menu des jeux.']
      action: '[MENU] jeux_menu'
