menu:
  id: 'settings_menu'
  title: '&8» &dParamètres'
  size: 45
  items:
    # --- Décorations (Vitres Violettes) ---
    decor_slots: '0,1,7,8,9,17,27,35,36,37,43,44'
    decor_item:
      material: 'PURPLE_STAINED_GLASS_PANE'
      name: '&7'
      action: '[NONE]'

    slot_11:
      material: 'hdb:3581'
      name: '&a&lMessages Privés'
      lore:
        - '&7Autorisez ou bloquez la réception'
        - '&7de messages privés.'
        - '&r'
        - '&8▸ &7Statut: %setting_private_messages_display%'
        - '&r'
        - '&a▶ Cliquez pour basculer !'
      action: '[COMMAND] settings toggle private_messages'

    slot_13:
      material: 'hdb:13389'
      name: '&e&lDemandes d''Amis'
      lore:
        - '&7Gérez qui peut vous envoyer'
        - '&7des demandes d''ami.'
        - '&r'
        - '&8▸ &7Statut: %setting_friend_requests_display%'
        - '&r'
        - '&a▶ Cliquez pour modifier !'
      action: '[COMMAND] settings toggle friend_requests'

    slot_40:
      material: 'hdb:9334'
      name: '&c&lRetour'
      lore:
        - '&7Revenir au menu profil.'
      action: '[MENU] profil_menu'
