menu:
  id: "settings_menu"
  title: "&8» &dParamètres"
  size: 45

  items:
    glass_1:
      slot: 0
      material: "PURPLE_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_2:
      slot: 1
      material: "PURPLE_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_3:
      slot: 7
      material: "PURPLE_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_4:
      slot: 8
      material: "PURPLE_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_5:
      slot: 36
      material: "PURPLE_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_6:
      slot: 44
      material: "PURPLE_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"

    private_messages:
      slot: 11
      material: "PLAYER_HEAD"
      head: "hdb:3581"
      name: "&a&lMessages Privés"
      lore:
        - "&7Autorisez ou bloquez la réception"
        - "&7de messages privés d'autres joueurs."
        - "&r"
        - "&8▸ &7Statut actuel: %setting_private_messages_status%"
        - "&r"
        - "&a▶ Cliquez pour basculer !"
      actions:
        - "[MESSAGE] &eParamètre basculé ! Messages privés: &cDésactivés"

    friend_requests:
      slot: 13
      material: "PLAYER_HEAD"
      head: "hdb:13389"
      name: "&e&lDemandes d'Amis"
      lore:
        - "&7Gérez qui peut vous envoyer"
        - "&7des demandes d'ajout en ami."
        - "&r"
        - "&8▸ &7Statut actuel: %setting_friend_requests_status%"
        - "&8▸ &7Options: Tous / Amis d'amis / Personne"
        - "&r"
        - "&a▶ Cliquez pour modifier !"
      actions:
        - "[MESSAGE] &eParamètre changé ! Demandes d'amis: &6Amis d'amis uniquement"

    group_requests:
      slot: 15
      material: "PLAYER_HEAD"
      head: "hdb:8537"
      name: "&b&lDemandes de Groupe"
      lore:
        - "&7Contrôlez qui peut vous inviter"
        - "&7dans des groupes de jeu."
        - "&r"
        - "&8▸ &7Statut actuel: %setting_group_requests_status%"
        - "&8▸ &7Options: Tous / Amis seulement / Personne"
        - "&r"
        - "&a▶ Cliquez pour ajuster !"
      actions:
        - "[MESSAGE] &eParamètre changé ! Demandes de groupe: &6Amis seulement"

    visibility:
      slot: 20
      material: "PLAYER_HEAD"
      head: "hdb:32010"
      name: "&f&lVisibilité des Joueurs"
      lore:
        - "&7Choisissez quels joueurs vous"
        - "&7voulez voir dans le lobby."
        - "&r"
        - "&8▸ &7Mode actuel: %setting_visibility_status%"
        - "&8▸ &7Options: Tous / Amis / Personne"
        - "&r"
        - "&a▶ Cliquez pour changer !"
      actions:
        - "[MESSAGE] &eParamètre changé ! Visibilité: &6Amis uniquement"

    notifications:
      slot: 22
      material: "PLAYER_HEAD"
      head: "hdb:1455"
      name: "&c&lNotifications"
      lore:
        - "&7Gérez les types de notifications"
        - "&7que vous souhaitez recevoir."
        - "&r"
        - "&8▸ &7Notifications d'amis: %notif_friends%"
        - "&8▸ &7Notifications de clan: %notif_clan%"
        - "&8▸ &7Notifications système: %notif_system%"
        - "&r"
        - "&a▶ Cliquez pour personnaliser !"
      actions:
        - "[MESSAGE] &eGestion des notifications en cours de développement !"

    audio:
      slot: 24
      material: "PLAYER_HEAD"
      head: "hdb:7439"
      name: "&6&lSons et Effets"
      lore:
        - "&7Activez ou désactivez les sons"
        - "&7et effets visuels du lobby."
        - "&r"
        - "&8▸ &7Sons d'interface: %setting_ui_sounds%"
        - "&8▸ &7Effets de particules: %setting_particles%"
        - "&8▸ &7Musique d'ambiance: %setting_music%"
        - "&r"
        - "&a▶ Cliquez pour ajuster !"
      actions:
        - "[MESSAGE] &eParamètres audio en cours de développement !"

    back:
      slot: 40
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir au menu profil."
      actions:
        - "[MENU] profil_menu"
