menu:
  id: "stats_menu"
  title: "&8» &bMes Statistiques"
  size: 54

  items:
    glass_1:
      slot: 0
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_2:
      slot: 1
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_3:
      slot: 2
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_4:
      slot: 6
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_5:
      slot: 7
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_6:
      slot: 8
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_7:
      slot: 9
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_8:
      slot: 17
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_9:
      slot: 45
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"
    glass_10:
      slot: 53
      material: "CYAN_STAINED_GLASS_PANE"
      name: "&7"
      actions:
        - "[NONE]"

    general_stats:
      slot: 13
      material: "PLAYER_HEAD"
      head: "hdb:2736"
      name: "&6&lStatistiques Générales"
      lore:
        - "&7Vos performances globales"
        - "&7sur le serveur."
        - "&r"
        - "&8▸ &7Parties jouées: &e0"
        - "&8▸ &7Victoires: &a0"
        - "&8▸ &7Défaites: &c0"
        - "&8▸ &7Ratio V/D: &60.0"
        - "&8▸ &7Expérience: &d0"
        - "&r"
        - "&7Cliquez pour plus de détails"
      actions:
        - "[MESSAGE] &eStatistiques détaillées en cours de développement !"

    bedwars_stats:
      slot: 20
      material: "PLAYER_HEAD"
      head: "hdb:67957"
      name: "&c&lBedWars"
      lore:
        - "&7Vos statistiques BedWars"
        - "&r"
        - "&8▸ &7Parties: &e0"
        - "&8▸ &7Victoires: &a0"
        - "&8▸ &7Kills: &c0"
        - "&8▸ &7Morts: &70"
        - "&8▸ &7Lits cassés: &60"
        - "&r"
        - "&a▶ Cliquez pour détails !"
      actions:
        - "[MESSAGE] &eStatistiques BedWars en cours de développement !"

    nexus_stats:
      slot: 22
      material: "PLAYER_HEAD"
      head: "hdb:38878"
      name: "&b&lNexus"
      lore:
        - "&7Vos statistiques Nexus"
        - "&r"
        - "&8▸ &7Parties: &e0"
        - "&8▸ &7Victoires: &a0"
        - "&8▸ &7Kills: &c0"
        - "&8▸ &7Morts: &70"
        - "&8▸ &7Nexus détruits: &60"
        - "&r"
        - "&a▶ Cliquez pour détails !"
      actions:
        - "[MESSAGE] &eStatistiques Nexus en cours de développement !"

    zombie_stats:
      slot: 24
      material: "PLAYER_HEAD"
      head: "hdb:23022"
      name: "&2&lZombie"
      lore:
        - "&7Vos statistiques Zombie"
        - "&r"
        - "&8▸ &7Parties: &e0"
        - "&8▸ &7Record: &60 vagues"
        - "&8▸ &7Zombies tués: &c0"
        - "&8▸ &7Temps de survie: &a0 min"
        - "&r"
        - "&a▶ Cliquez pour détails !"
      actions:
        - "[MESSAGE] &eStatistiques Zombie en cours de développement !"

    custom_stats:
      slot: 26
      material: "PLAYER_HEAD"
      head: "hdb:60776"
      name: "&6&lJeux Inédits"
      lore:
        - "&7Vos statistiques dans les"
        - "&7modes de jeu exclusifs."
        - "&r"
        - "&8▸ &7Parties: &e0"
        - "&8▸ &7Victoires: &a0"
        - "&8▸ &7Mode favori: &6Aucun"
        - "&r"
        - "&a▶ Cliquez pour détails !"
      actions:
        - "[MESSAGE] &eStatistiques Jeux Inédits en cours de développement !"

    retour:
      slot: 49
      material: "PLAYER_HEAD"
      head: "hdb:9334"
      name: "&c&lRetour"
      lore:
        - "&7Revenir au menu profil."
      actions:
        - "[MENU] profil_menu"
